### ISSUE TITLE
Cannot update to Error Prone `2.4.0`: strange compiler error on migration

### ISSUE THREAD

**Issue by serhii-lekariev** [SpineEventEngine/config#127]
Upgrading to Error Prone `2.4.0` causes a compiler error in one, potentially many, of our repositories. 

If an enum declares a constant that defines a method with a Javadoc that contains a ` {@link }` to some class, Error Prone `2.4.0` causes the compilation to fail, while Error Prone `2.3.4` doesn't.

`core-java` declares an enum like that: https://github.com/SpineEventEngine/core-java/blob/master/server/src/main/java/io/spine/server/model/MatchCriterion.java#L122  

This issue is not Gradle related: I've been able to reproduce this using Maven. JDK version has nothing to do with either: the compiler error is emitted on JDKs 8, 11 and 13.

A small example can be found [here](https://github.com/serhii-lekariev/error-prone-error-repro).
I've submitted a [report](https://github.com/google/error-prone/issues/1693) to Error Prone.

**Comment by yuri-sergiichuk** [comment]
Our repos are already migrated to Error Prone `2.4.0`. `core-java` was migrated as part of the https://github.com/SpineEventEngine/core-java/pull/1319.
