### ISSUE TITLE
Update `detekt` and corresponding GitHub worklfow

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/config#363]
See this [issue from `tool-base`](https://github.com/SpineEventEngine/tool-base/issues/22) which describes the problem when migrating to newer version.

We probably may need to resolve this issue, if #412 is addressed.

**Comment by alexander-yevsyukov** [comment]
Also, we should run `detekt` during build time locally so that we spot these issues earlier. 

It takes much roundtrip time to suppress and address them once they are discovered only at CI.

**Comment by yevhenii-nadtochii** [comment]
I'm closing this issue as #412 has been addressed. 

Detekt is now used during build time.
