### ISSUE TITLE
Generate `pom.xml` in all projects for using GitHub dependency check

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/config#37]
For Java GitHub only [supports Maven via pom.xml](https://help.github.com/articles/listing-the-packages-that-a-repository-depends-on/).

We can get security checks and seeing dependency graph via GitHub if we add `pom.xml` generation and checking it into the `master` during the publishing.

The idea is to use Gradle Maven plugin for that.

**Comment by JuliaEvseeva** [comment]
@armiol this information is also needed to display licenses on the spine.io site.
Please make the priority of this issue higher.

**Comment by armiol** [comment]
@serhii-lekariev please add this task into your current work pipeline.
@dmdashenkov FYI.
