### ISSUE TITLE
Use detekt in Gradle builds rather than in a GitHub workflow

### ISSUE THREAD

**Issue by alexander-yevsyukov** [SpineEventEngine/config#412]
It's too late to check such things at GitHub. 
Things reported against test or `buildSrc` code are usually not relevant.

Let's take the build settings from [detekt](https://github.com/detekt/detekt) and apply to our builds.

**Comment by yevhenii-nadtochii** [comment]
I'm going to use this task list to track issue progress:

- [x] config
- [x] base
- [ ] core-java
- [ ] SpineEventEngine.github.io
- [ ] jdbc-storage
- [ ] dashboard
- [ ] users
- [ ] deployment
- [ ] client-cpp
- [ ] firebase-storage
- [ ] time
- [ ] money
- [ ] cli
- [ ] bootstrap
- [ ] auth
- [ ] dart
- [ ] roles
- [ ] chat-bot
- [ ] publishing
- [ ] embed-code
- [ ] backlog
- [ ] site-backend
- [ ] feedback
- [ ] organizations
- [ ] template
- [ ] .github
- [ ] features
- [ ] ProtoData
- [ ] gcp-emulators
- [ ] validation
- [ ] message-delivery
- [ ] base-types
- [ ] model-compiler
- [ ] mc-java
- [ ] gradle-execfork-plugin
- [ ] terraform-google-spine-liquor
- [ ] doc-tools
- [ ] tool-base
- [ ] mc-js
- [ ] mc-dart
- [ ] examples
- [ ] documentation
- [ ] dokka-tools
- [ ] model-tools
- [ ] text
- [ ] change

Will not be updated within this issue:

- [ ] web
- [ ] gcloud-java

**Comment by armiol** [comment]
Some of these are archived. And also, `jdbc-storage` is not yet to be updated. 

Just FYI. You'll see as you go.

**Comment by alexander-yevsyukov** [comment]
@yevhenii-nadtochii, I've reduced the list and grouped repositories by stages, so that we get results on more important faster.

**Comment by yevhenii-nadtochii** [comment]
The corresponding `detekt-code-analysis` script-plugin has been implemented in `config`. And it has been applied to repositories where appropriate.

Can we close this issue?

**Comment by alexander-yevsyukov** [comment]
@yevhenii-nadtochii you decide.
