### ISSUE TITLE
Enable audit of NPM packages in JS build tasks.

### ISSUE THREAD

**Issue by YegorUdovchenko** [SpineEventEngine/config#64]
The `auditNodePackages` Gradle task defined in `config/gradle/js/build-tasks.gradle` was disabled. 
This task executes `npm audit` command to audit the module dependencies but sometimes it fails due to overload of NPM registry service according to [this](https://npm.community/t/enoaudit-from-registry-npmjs-org-503/4642) issue.

The frequency of these failures is unpredictable and causes builds to fail.

**Comment by dmdashenkov** [comment]
Considering the task is now [enabled by default](https://github.com/SpineEventEngine/config/pull/98), should we close this?

**Comment by dmdashenkov** [comment]
The problem [persists](https://travis-ci.com/github/SpineEventEngine/web/builds/153544246).
@armiol, @dmitrykuzmin, I suggest we turn off the check. Security vulnerabilities are checked by GitHub now via the [dependencies](https://github.com/SpineEventEngine/web/network/dependencies) feature.

**Comment by dmitrykuzmin** [comment]
@armiol, @dmdashenkov we can probably close this now.
